services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "23306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
